<?php

function cards_menu() {
  $friends = ['Jim Joe', 'Frankenstein', 'Turtleman'];
  $items = array();
  foreach($friends as $friend) {
    $items['cards/' . $friend] = array(
      'title' => 'Greetings ' . $friend,
      'page callback' => 'greeting_card',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
      'page arguments' => array($friend)
    );
  };
  return $items;
}

function greeting_card($friend) {
  return "<h2>Hey, $friend!</h2>
          <p>I know it's been a while, but Epicodus
          is keeping me real busy!  I hope you're doing well.  How's old
          so-and-so?  Still doing such-and-such?  Well I gotta go, take care!
          </p>
          <p>Sarcastically,</p>
          <p>Sam and Jordan</p>
          ";
}
