<?php

function pet_menu() {
  $items = array();
  $items['my_pet'] = array(
    'title' => 'My Pet Project (Badum-ch!)',
    'page callback' => 'pet_info',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}

function pet_info() {
  return '
    <img width="90%" src="sites/all/modules/pet/Artax.jpg">
    <p><a href="https://en.wikipedia.org/wiki/Artax_(horse)">Info on Artax</a></p>
    <p><a href="https://youtu.be/y688upqmRXo">Goodbye, old friend.</a></p>
  ';
}
